### ISSUE TITLE
Please tag the releases

### ISSUE THREAD

**Issue by noscript** [jpetrie/vim-counterpoint#13]
Plugin managers like vim-plug don't allow to lock to certain sha1 revisions.

**Comment by jpetrie** [comment]
I don't use vim-plug. Will it be sufficient to simply go back and `git tag -a v1.X <some commit hash>`? Or is there a specific GitHub-related thing I should do to enable this?

**Comment by noscript** [comment]
>> Will it be sufficient to simply go back and git tag -a v1.X <some commit hash>? 

yes. You would need to do
```
git tag -a v1.3 c0eac45
git tag -a v1.2 9721b32
# ... and so on
git push --tags
```

Same thing can be done via GitHub using "Draft a new release" button.

>> Or is there a specific GitHub-related thing I should do to enable this?

it's pure git thing

**Comment by jpetrie** [comment]
Okay, done, please let me know if it doesn't work.
