### ISSUE TITLE
Add the ability to use split windows

### ISSUE THREAD

**Issue by embear** [jpetrie/vim-counterpoint#6]
Hi,

first of all thanks for the plugin. Before I had been using the unmaintained "a.vim" plugin and I am happy that there is an alternative to that.

Now to the feature request: Could you add commands that do not change the file in the current window but open the next file in a new window or in a new tab? Additionally it would be great if it just switches to the window/tab if the file is already open. It should be possible to enable and disable the switching of windows. I think not every user will like that behavior.

**Comment by jpetrie** [comment]
I have some reservations about this; I may need convincing. Mainly I'm concerned about contributing to the misunderstandings many users have with windows and tabs in vim.

Not only does using tabs in this fashion seem counter to what they actually represent in vim (layouts of windows), I'm also not sure how I'd even go about doing it. For windows, I can do it with `bufwinnr`, but I'm not aware of a similar function or technique for doing the same with tabs and I'm not sure I'd want to support it even if it existed.

Splitting windows is probably reasonable. There are a few edge cases that might put users in an unexpected spot (when they more than one window viewing a buffer, or previously had a buffer open in a window and thought vim would "remember" that), but I can accept those as things users would need educating about, I think.

**Comment by jpetrie** [comment]
My current thinking for this is as follows:

- The cycling commands can use the postfix bang to indicate that they should try to switch you to an existing window on the target buffer if it exists.
- The cycling commands can also take arguments which are used to define the command that will be run to actually edit the target file; if omitted, the behavior will be as if you passed "edit" as the argument.

This should let you encapsulate the window splitting behavior you outlined. For example, in your `.vimrc`,

    nnoremap <leader>a :CounterpointNext! aboveleft vsplit

will map a command that tries to split the window vertically and open the counterpart on the left, unless the counterpart is already open in another window (in which case you are switched to that window instead).

I'm not 100% sure this is the best approach for the long term, but if you want you can pull the `issue-6` branch now and try it out. It should work.

**Comment by embear** [comment]
The proposed extension looks really promising to me. I think I can use the extended command to address all my use cases.

Important is the ability to split the window for source and header so I can see them both at the same time. Being able to so this with a single command would help me very much.

Thanks for your effort!

**Comment by jpetrie** [comment]
Merged to master.
